# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=25, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'Chair',
                'verbose_name_plural': 'Chairs',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=25, verbose_name='Обозначение')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chair_courses', to='courses.Chair')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
