# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='slug',
            field=models.SlugField(default='hmath', max_length=25, verbose_name='Обозначение'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='hmath', max_length=25, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
