# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20161119_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='Обозначение'),
        ),
    ]
