# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.IntegerField(choices=[(1, 'UP'), (-1, 'DOWN')])),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
        migrations.DeleteModel(
            name='PostVote',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'object_id', 'content_type')]),
        ),
    ]
