# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(None, 'Ваша должность'), ('Студент', 'Студент'), ('Преподаватель', 'Преподаватель')], max_length=25, verbose_name='должность'),
        ),
    ]
