# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161119_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(None, 'Ваша должность'), ('Student', 'Студент'), ('Teacher', 'Преподаватель')], max_length=25, verbose_name='должность'),
        ),
    ]
